
# version: "3.9"
services:
  database:
    user: root
    # a imagem esta no docker file para compilação da imagem
    build: .
    #image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev-mssql2022
    hostname: dev-mssql2022    
    #privileged: true    
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Root@mssql2021
      #- MSSQL_PID= #Express 
    volumes:
      - /home/dev/reposit/dados/mssql2022/data:/var/opt/mssql/data
      - /home/dev/reposit/dados/mssql2022/log:/var/opt/mssql/log
    networks:
      - rededev
volumes:
  dados:
    name: db-mssql2022
networks:
  rededev:
    external: true
    name: netdev