
# version: "3.9"
services:
  mssql:
    #image: mcr.microsoft.com/mssql/server:2017-latest
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: dev-mssql
    # hostname: dev-mssqlexpress
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Root@mssql2021 #MSSQL_SA_PASSWORD=Root@mssql2021
      - MSSQL_PID=Express 
    volumes:
      - /home/dev/reposit/dados/mssql2022/data:/var/opt/mssql/data
      - /home/dev/reposit/dados/mssql2022/log:/var/opt/mssql/log
    networks:
      - rededev
volumes:
  dados:
    name: db-mssql2022
networks:
  rededev:
    external: true
    name: netdev