version: '3.9'
services:
  db:
    image: mariadb:lts
    container_name: dev-mariadb10
    hostname: dev-mariadb10
    ports:
      - 3306:3306
    volumes:
      - ../../yml-data/db-mariadb10/:/var/lib/mysql  
    environment:
      - MARIADB_ROOT_PASSWORD=devroot
      - MARIADB_DATABASE=devlincred
      - MARIADB_USER=devlincred
      - MARIADB_PASSWORD=devlincred123
    networks:
      - rededev
volumes:
  mdb10dados:
    name: db-mariadb10  
networks:
  rededev:
    external: true
    name: netdev
