version: "3.9"

services:

  #db:
  # image: mysql:8.0
  #  container_name: dev-wordpress-mysql8
  #  ports:
  #    - "3306:3306"
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: dev
  #    MYSQL_USER: wordpress
  #    MYSQL_PASSWORD: wordpress
  #    MYSQL_DATABASE: wordpress
  #  volumes:
  #    - ./mysqldata:/var/lib/mysql

  wordpress:
  #  depends_on:
  #    - db
    image: wordpress
    container_name: dev-wordpress
    hostname: dev-wordpress
    ports:
      - 8080:80
    restart: always      
    environment:
      #WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_HOST: dev-mysql8:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../../app-wordpress/wphtml:/var/www/html

volumes:
  wphtml:
  
networks:
  default:
    external:
      name: netdev