
# version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: dev-mssql
    # hostname: dev-mssqlexpress
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Root@mssql2021
      - MSSQL_PID=Express 
    volumes:
      - /home/dev/reposit/dados/mssqlexpress/data:/var/opt/mssql/data
      - /home/dev/reposit/dados/mssqlexpress/log:/var/opt/mssql/log
    networks:
      - rededev
volumes:
  dados:
    name: db-mssqlexpress 
networks:
  rededev:
    external: true
    name: netdev