version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    #build: .
    container_name: dev-postgresql14.1
    hostname: dev-postgresql14
    ports:
      - 5432:5432
    volumes:
      - /home/dev/reposit/dados/pgsql14.1/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: application-dev

volumes:
  data:
    
networks:
  default:
    external:
      name: netdev
