# version: "3.9"
services:
  db:
    image: postgres:16.3-alpine
    #build: .
    container_name: dev-pgsql163
    hostname: dev-pgsql163
    ports:
      - 5432:5432
    volumes:
      - /home/dev/reposit/dados/pgsql16.3/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: representa_dev
    networks:
      - rededev
volumes:
  mdb10dados:
    name: db     
networks:
  rededev:
    external: true
    name: netdev
