# Use root/example as user/password credentials
version: "3.9"
services:
    db:
        image: mongo
        restart: always
        container_name: dev-mongo
        hostname: dev-mongo
        ports:
            - 27017:27017
        volumes:
            - ../../db-mongo/dados:/data/db  
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev
            MONGO_INITDB_ROOT_PASSWORD: dev

    express:
        image: mongo-express
        restart: always
        container_name: dev-mongo-express
        hostname: dev-mongo=express
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: dev
            ME_CONFIG_MONGODB_ADMINPASSWORD: dev

networks:
    default:
        external:
            name: netdev
 