# version: '3.9'
services:
  firebird3:
    build: .
    container_name: dev-fb3
    hostname: dev-fb3
    ports:
      - 3050:3050
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_DATABASE=datacred4.fdb
      - FIREBIRD_USER=sysdba
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_PORT=3050
    volumes:
      - /home/dev/reposit/dados/fb3-db/backup:/firebird/backup      
      - /home/dev/reposit/dados/fb3-db/data:/firebird/data 
      - /home/dev/reposit/dados/fb3-db/data/databases.conf:/etc/firebird/3.0/databases.conf      
    networks:
      - rededev
volumes:
  fb3dados:
    name: dados  
networks:
  rededev:
    external: true
    name: netdev      